import { buildRuntimePlanView } from "./runtimePlan";
import type { ExecutionPlan, RuntimeBundleResponse } from "../types/runtime";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

const bundle: RuntimeBundleResponse = {
  runtime: {
    runtime_id: "runtime-phase3",
    project_id: "project-phase3",
    company_name: "Adaptive Runtime",
    org_graph: {
      zones: {
        strategy_hub: { label: "Strategy Hub", accent_color: "#14B8A6", row: 0, col: 3 },
      },
      reporting_lines: [
        { from: "ceo", to: "pm", label: "Direction" },
        { from: "pm", to: "development_team", label: "Delivery" },
      ],
    },
    meeting_protocol: {
      default_roles: ["ceo", "pm"],
      include_assigned_agents: true,
      include_approvers: true,
      layout: "briefing",
    },
    approval_graph: {
      escalation_roles: ["ceo"],
    },
    shared_boards: {},
    execution_mode: "assisted",
    owner_ops_state: {},
    agent_instance_ids: ["inst-ceo", "inst-pm", "inst-dev", "inst-design"],
    created_at: "2026-03-26T00:00:00.000Z",
    updated_at: "2026-03-26T00:00:00.000Z",
  },
  blueprints: [
    {
      id: "bp-ceo",
      name: "CEO",
      role_label: "ceo",
      capabilities: ["strategy", "approval"],
      prompt_bundle_ref: null,
      skill_bundle_refs: [],
      tool_policy: {},
      permission_policy: {},
      memory_policy: {},
      collaboration_policy: {},
      approval_policy: {},
      ui_profile: {
        display_name: "CEO",
        title: "CEO",
        avatar_style: "pixel",
        accent_color: "#8B5CF6",
        icon: "Crown",
        home_zone: "ceo_office",
        team_affinity: "executive_team",
        authority_level: 10,
        capability_tags: ["strategy"],
        primary_widgets: ["kpi", "approval_queue"],
        secondary_widgets: ["timeline"],
        focus_mode: "strategy",
        meeting_behavior: "chair",
      },
      is_builtin: true,
      owner_user_id: "system",
      created_at: "",
      updated_at: "",
    },
    {
      id: "bp-pm",
      name: "PM",
      role_label: "pm",
      capabilities: ["planning", "coordination"],
      prompt_bundle_ref: null,
      skill_bundle_refs: [],
      tool_policy: {},
      permission_policy: {},
      memory_policy: {},
      collaboration_policy: {},
      approval_policy: {},
      ui_profile: {
        display_name: "PM",
        title: "PM",
        avatar_style: "pixel",
        accent_color: "#6366F1",
        icon: "ClipboardList",
        home_zone: "meeting_room",
        team_affinity: "executive_team",
        authority_level: 8,
        capability_tags: ["planning"],
        primary_widgets: ["kanban", "execution_graph"],
        secondary_widgets: ["timeline"],
        focus_mode: "coordination",
        meeting_behavior: "facilitate",
      },
      is_builtin: true,
      owner_user_id: "system",
      created_at: "",
      updated_at: "",
    },
    {
      id: "bp-dev",
      name: "Frontend",
      role_label: "developer_front",
      capabilities: ["code_generation", "frontend"],
      prompt_bundle_ref: null,
      skill_bundle_refs: [],
      tool_policy: {},
      permission_policy: {},
      memory_policy: {},
      collaboration_policy: {},
      approval_policy: {},
      ui_profile: {
        display_name: "Frontend",
        title: "Frontend",
        avatar_style: "pixel",
        accent_color: "#3B82F6",
        icon: "Code",
        home_zone: "rd_lab",
        team_affinity: "development_team",
        authority_level: 6,
        capability_tags: ["frontend"],
        primary_widgets: ["code", "git"],
        secondary_widgets: ["timeline"],
        focus_mode: "build",
        meeting_behavior: "report",
      },
      is_builtin: true,
      owner_user_id: "system",
      created_at: "",
      updated_at: "",
    },
    {
      id: "bp-design",
      name: "Designer",
      role_label: "designer",
      capabilities: ["design", "review"],
      prompt_bundle_ref: null,
      skill_bundle_refs: [],
      tool_policy: {},
      permission_policy: {},
      memory_policy: {},
      collaboration_policy: {},
      approval_policy: {},
      ui_profile: {
        display_name: "Designer",
        title: "Designer",
        avatar_style: "pixel",
        accent_color: "#F97316",
        icon: "Palette",
        home_zone: "design_studio",
        team_affinity: "creative_team",
        authority_level: 5,
        capability_tags: ["design"],
        primary_widgets: ["preview", "assets"],
        secondary_widgets: ["timeline"],
        focus_mode: "visual",
        meeting_behavior: "observe",
      },
      is_builtin: true,
      owner_user_id: "system",
      created_at: "",
      updated_at: "",
    },
  ],
  instances: [
    {
      instance_id: "inst-ceo",
      blueprint_id: "bp-ceo",
      project_id: "project-phase3",
      runtime_status: "working",
      assigned_team: "executive_team",
      current_tasks: ["Approve release"],
      context_window_state: {},
      memory_bindings: {},
      live_metrics: {},
      created_at: "",
      updated_at: "",
    },
    {
      instance_id: "inst-pm",
      blueprint_id: "bp-pm",
      project_id: "project-phase3",
      runtime_status: "working",
      assigned_team: "executive_team",
      current_tasks: ["Coordinate launch"],
      context_window_state: {},
      memory_bindings: {},
      live_metrics: {},
      created_at: "",
      updated_at: "",
    },
    {
      instance_id: "inst-dev",
      blueprint_id: "bp-dev",
      project_id: "project-phase3",
      runtime_status: "waiting_approval",
      assigned_team: "development_team",
      current_tasks: ["Implement approval UI"],
      context_window_state: {},
      memory_bindings: {},
      live_metrics: {},
      created_at: "",
      updated_at: "",
    },
    {
      instance_id: "inst-design",
      blueprint_id: "bp-design",
      project_id: "project-phase3",
      runtime_status: "idle",
      assigned_team: "creative_team",
      current_tasks: [],
      context_window_state: {},
      memory_bindings: {},
      live_metrics: {},
      created_at: "",
      updated_at: "",
    },
  ],
};

const completedPlan: ExecutionPlan = {
  plan_id: "plan-completed",
  runtime_id: "runtime-phase3",
  goal: "Archive prior sprint",
  created_by: "inst-pm",
  status: "completed",
  created_at: "2026-03-25T00:00:00.000Z",
  updated_at: "2026-03-25T00:00:00.000Z",
  steps: [
    {
      step_id: "old-1",
      label: "Archive",
      description: "Archive old sprint board",
      assigned_to: "inst-pm",
      depends_on: [],
      approval_required_by: null,
      status: "completed",
      input: {},
      output: {},
      started_at: null,
      completed_at: null,
    },
  ],
};

const activePlan: ExecutionPlan = {
  plan_id: "plan-active",
  runtime_id: "runtime-phase3",
  goal: "Ship adaptive phase three",
  created_by: "inst-pm",
  status: "paused",
  created_at: "2026-03-26T00:00:00.000Z",
  updated_at: "2026-03-26T00:00:00.000Z",
  steps: [
    {
      step_id: "step-1",
      label: "Frame scope",
      description: "Break work into lanes",
      assigned_to: "inst-pm",
      depends_on: [],
      approval_required_by: null,
      status: "completed",
      input: {},
      output: {},
      started_at: null,
      completed_at: null,
    },
    {
      step_id: "step-2",
      label: "Implement UI",
      description: "Ship runtime-aware widgets",
      assigned_to: "inst-dev",
      depends_on: ["step-1"],
      approval_required_by: "inst-ceo",
      status: "awaiting_approval",
      input: {},
      output: {},
      started_at: null,
      completed_at: null,
    },
    {
      step_id: "step-3",
      label: "Polish motion",
      description: "Finalize execution overlay",
      assigned_to: "inst-design",
      depends_on: ["step-2"],
      approval_required_by: null,
      status: "blocked",
      input: {},
      output: {},
      started_at: null,
      completed_at: null,
    },
  ],
};

const view = buildRuntimePlanView(bundle, [completedPlan, activePlan]);

assert(view.activePlan?.plan_id === "plan-active", "paused/active plan should be selected over completed plans");
assert(view.approvalQueue.length === 1, "awaiting approval step should create one approval item");
assert(view.approvalQueue[0]?.step_id === "step-2", "approval queue should reference the awaiting approval step");
assert(view.approvalQueue[0]?.approver_role_label === "ceo", "approval queue should resolve approver role");
assert(view.meeting.participant_ids.includes("inst-ceo"), "meeting should include default executive approvers");
assert(view.meeting.participant_ids.includes("inst-pm"), "meeting should include default planning role");
assert(view.meeting.participant_ids.includes("inst-dev"), "meeting should include assigned runtime agent");
assert(!view.meeting.participant_ids.includes("inst-design"), "blocked downstream contributors should not join briefing by default");
assert(view.execution.nodes.length === 3, "execution view should include every step node");
assert(view.execution.edges.length === 2, "execution view should include dependency edges");
assert(view.org.clusters.some((cluster) => cluster.id === "executive_team"), "org view should cluster agents by team");
assert(view.org.edges.some((edge) => edge.label === "Delivery"), "org view should preserve reporting lines");

console.log("runtimePlan tests passed");
