import json
from unittest.mock import MagicMock
from daacs.orchestrator import DAACSOrchestrator
from daacs.context.types import RFIResult

class SmartMockLLM:
    """
    Simulates the intelligence of the Planner for the 'Calculator' scenario.
    Responses change based on the prompt's assumptions/context.
    """
    def execute(self, prompt: str) -> str:
        prompt_lower = prompt.lower()
        
        # Check for specific constraints generated by the Provider
        is_design_focused = "constraint: prioritize design quality" in prompt_lower
        is_mvp_focused = "constraint: prioritize rapid development" in prompt_lower
        
        # Scenario 2: Design Focus
        if is_design_focused:
             return json.dumps({
                "goal": "Build a Polished Web Calculator (Design First)",
                "specs": [
                     {
                        "id": "TECH-FE", "type": "tech", "title": "Next.js + Shadcn UI",
                        "description": "Framework for high-quality UI/UX",
                        "rationale": "Switching to Next.js/Shadcn per 'Design' focus",
                        "tech_category": "Frontend",
                        "sources": ["https://ui.shadcn.com", "https://nextjs.org"]
                    },
                    {
                        "id": "FR-01", "type": "feature", "title": "Responsive Layout",
                        "description": "Mobile-first responsive grid",
                        "status": "accepted"
                    },
                    {
                        "id": "FR-02", "type": "feature", "title": "Theme Toggle",
                        "description": "Dark/Light mode support",
                        "status": "accepted"
                    }
                ],
                "blueprint": {
                    "mermaid_script": "graph TD; Layout-->Header; Layout-->Calculator; Calculator-->ThemeToggle",
                    "components": ["Layout", "Header", "Calculator", "ThemeToggle"]
                }
            })

        # Scenario 1: Initial (MVP Focus) / Default
        if is_mvp_focused or "mvp" in prompt_lower:
            return json.dumps({
                "goal": "Build a Simple Web Calculator (MVP)",
                "specs": [
                    {
                        "id": "TECH-FE", "type": "tech", "title": "React + Vite",
                        "description": "Standard modern web stack",
                        "rationale": "Chosen for speed and MVP alignment",
                        "tech_category": "Frontend",
                        # The system should inject these from context, but we mock the result here
                        "sources": ["https://react.dev", "https://vitejs.dev"]
                    },
                    {
                        "id": "FR-01", "type": "feature", "title": "Basic Arithmetic",
                        "description": "Add, Subtract, Multiply, Divide",
                        "status": "accepted"
                    }
                ],
                "blueprint": {
                    "mermaid_script": "graph TD; App-->Calculator; Calculator-->Display; Calculator-->Keypad",
                    "components": ["App", "Calculator", "Display", "Keypad"]
                }
            })
            
        # Fallback
        return json.dumps({"goal": "Unknown", "specs": [], "blueprint": None})

def run_demo():
    print("--- 🎬 Phase 5: Final Scenario Demo (Calculator) ---")
    
    # 1. Setup Orchestrator
    orch = DAACSOrchestrator()
    # Mock the LLM
    orch.agent.client.execute = MagicMock(side_effect=SmartMockLLM().execute)
    
    # 2. Simulate User Request "Simple Calculator"
    print("\nStep 1: User asks for 'Simple Calculator' (Assumption: MVP)")
    # We manually drive the flow to ensure we capture the tech context step
    initial_goal = "Create a simple web calculator"
    
    # Simulate RFI Parsing
    rfi = RFIResult(language="javascript", platform="web", ui_required=True, constraints=["mvp"])
    # Fetch Context (Real DuckDuckGo execution)
    print(">> Fetching Real-time Tech Context from Web (DuckDuckGo)...")
    # Force web provider if not set (it should given the previous verification)
    if "Mock" in type(orch.tech_context_provider.search).__name__:
         print("(Warning: Using Mock Search, exporting env var needed for Real)")
         
    ctx = orch.tech_context_provider.fetch(rfi, orch.assumptions)
    orch.tech_context = ctx
    print(f"   Fetched {len(ctx.facts)} facts, {len(ctx.sources)} sources.")
    if ctx.sources:
        print(f"   Source Sample: {ctx.sources[0]}")
    
    # Generate Plan (MVP)
    print(">> Generating Plan 1 (MVP Focus)...")
    # Including 'mvp' in history to trigger SmartMockLLM 'mvp' path
    plan1_str = orch.agent.finalize_rfp("User: Simple calculator. System: MVP focus.", ctx.__dict__)
    plan1 = json.loads(plan1_str)
    print(f"   Tech Choice: {plan1['specs'][0]['title']}")
    print(f"   Rationale: {plan1['specs'][0]['rationale']}")
    
    # 3. Simulate Assumption Change -> Design
    print("\nStep 2: User changes Assumption to 'Design Focus'")
    print(">> Updating Assumptions...")
    orch.assumptions.primary_focus = "design"
    orch.assumptions.options["scalability"] = False
    
    # Recalculate Context (Context might change if query builder used assumptions, but here facts remain similar)
    # Re-Generate Plan (Design)
    ctx = orch.tech_context_provider.fetch(rfi, orch.assumptions)
    
    print(">> Generating Plan 2 (Design Focus)...")
    # Including 'design' in history to trigger SmartMockLLM 'design' path
    plan2_str = orch.agent.finalize_rfp("User: Simple calculator. System: Design focus.", ctx.__dict__)
    plan2 = json.loads(plan2_str)
    
    print(f"   Tech Choice: {plan2['specs'][0]['title']}")
    print(f"   Rationale: {plan2['specs'][0]['rationale']}")
    
    # Verification
    if plan1['specs'][0]['title'] != plan2['specs'][0]['title']:
        print("\n✅ SUCCESS: Architecture changed based on Assumption drift!")
    else:
        print("\n❌ FAIL: Architecture did not change.")

if __name__ == "__main__":
    run_demo()
